# Generated by Django 5.0.6 on 2024-06-07 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('UserAdmin', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('contrasenaAdmin', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='NumeroAtencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=2)),
                ('ubicacion', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tramite',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('nombreTramite', models.CharField(max_length=30)),
                ('fecha', models.DateField()),
            ],
        ),
    ]
