# Generated by Django 5.0.6 on 2024-06-14 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TramiFast', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TramiteVisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreV', models.CharField(max_length=20)),
                ('apellidoV', models.CharField(max_length=30)),
                ('paisV', models.CharField(max_length=30)),
                ('motivodeV', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='numeroatencion',
            name='ubicacion',
            field=models.CharField(max_length=30),
        ),
    ]
