# Generated by Django 5.0.6 on 2025-05-17 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FerreMas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('contraseña', models.CharField(max_length=128)),
                ('tipo', models.CharField(choices=[('vendedor', 'Vendedor'), ('bodeguero', 'Bodeguero'), ('contador', 'Contador')], max_length=20)),
                ('primera_vez', models.BooleanField(default=True)),
            ],
        ),
    ]
